### ISSUE TITLE
Update photo in README.md to show new e2e test location and with new name

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab3_angular-javalin#1070]
The default location is e2e now. I believe that Cypress was trying to be different and use "integration", but they seem to now have a default of e2e like Protractor did. For now, I put text in because I don't have the brain cells to update the picture. Just a note that it would be good to do that.

**Comment by kklamberty** [comment]
![Location of testing code](https://user-images.githubusercontent.com/302297/108024936-25605500-6feb-11eb-87e5-829d4e9de44a.png)

**Comment by kklamberty** [comment]
Also, the cypress tests now have a different name, and at least one place in the lab tells students to look for `user-list.spec.ts` when it's now called `user-list.cy.ts`.

**Comment by NicMcPhee** [comment]
This was resolved by #1211
