### ISSUE TITLE
Add support for (page) titles

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-javalin#20]
At the moment the page title stays the same no matter where you are in the app, and it would be nice to have that update to reflect where you are. It looks like [this Angular tutorial page](https://angular.io/docs/ts/latest/cookbook/set-document-title.html) probably walks us through it.

**Comment by NicMcPhee** [comment]
I poked at this for a few minutes and got lost in how to access the function being defined in the `AppComponent`. My guess is that the solution is very simple, but I didn't see how/where. Thus I'm backing away since this isn't really a priority.

**Comment by jpwalbran** [comment]
[Upon a little bit of poking around](https://dev.to/brandontroberts/setting-page-titles-natively-with-the-angular-router-393j), it looks like there's a good way to do this in angular 14, but not beforehand. Doing this in Angular <14 seems like it would add a lot of extra code that doesn't end up accomplishing all that much.

**Comment by NicMcPhee** [comment]
I was assuming we'd probably want to try to upgrade to V14 anyway? The Iteration Template is upgraded to V14, although it looks like that was never rolled back to this lab (or the Angular tutorial, I suspect).

**Comment by NicMcPhee** [comment]
This was resolved somewhere. E2E tests were added in #1081 by @jpwalbran.
