### ISSUE TITLE
Unit (Karma) tests fail with --watch=false

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-javalin#519]
`ng test` passes fine. `ng test --watch=false` passes all the tests, and then fails at the end with:

```
TOTAL: 22 SUCCESS
Chrome 88.0.4324.150 (Mac OS 10.15.7) ERROR
  Some of your tests did a full page reload!
```

No idea if this happened in the past, but I don't remember it and don't know why it's happening now. [Some searching](https://github.com/karma-runner/karma/issues/3560) suggests this was a recent problem in Karma but should be fixed in the version we have in the Spring 2021 branch.

I don't know if this will interact badly with the GitHub Actions since they presumably only run the tests once?

**Comment by helloworld12321** [comment]
This issue seems to be Mac-specific, from what we can tell. (At least, we weren't able to reproduce it on Windows.)

**Comment by NicMcPhee** [comment]
This doesn't seem to happen anymore, even on Macs, so I assume that some updates somewhere made this go away. I'm going to close it for now, and we can re-open it if someone finds it happening again.
