### ISSUE TITLE
Improve error handling in `user-list.component.ts`

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-javalin#520]
Currently `UserListComponent.getUsers()` just does `console.log` when there's an error when it requests users. This isn't great, and we should probably replace this with something that provides an example of what we'd like students to do when something like this happens.

What would be reasonable? A dialog indicating that there's been an error getting data from the server?

**Comment by helloworld12321** [comment]
Sure! Some sort of snackbar, maybe?

**Comment by NicMcPhee** [comment]
It looks like I at least partially approached this in #514 last year. I left a comment saying I'd like to throw an error, but that when I did that I had problems with the testing so it's commented out. Is throwing an error even the "right" thing to do here? Is the snackbar enough and we should just close this?

**Comment by helloworld12321** [comment]
I think `throw` probably isn't the right thing to do here, actually!

`throw` is for when you want to communicate failure to other pieces of code—ie, this is a problem that the _caller_ should handle. (And if the caller can't handle the problem, it should just explode.)

If you just want to communicate "Yo, something went wrong!" to the _user_ of the app, then a snackbar or a `console.error` call (or both) should suffice.

**Comment by helloworld12321** [comment]
So I'd probably recommend:

1. Deleting the comment about throwing an error here (https://github.com/UMM-CSci-3601/3601-lab3_angular-javalin/blob/fdb6dce43e34ae975f6680fbf2ac88a6c4253f00/client/src/app/users/user-list.component.ts#L49)
2. Possibly adding a `console.error()` call
3. Closing this issue.

**Comment by helloworld12321** [comment]
Note in particular that `console.error()` includes a stack trace along with its message 🙂

**Comment by NicMcPhee** [comment]
Very nicely put. I'll try to do that over the weekend and reshare. Thanks!
